### ISSUE TITLE
Vizceral canvas always height = 0

### ISSUE THREAD

**Issue by rickfast** [Netflix/vizceral-react#2]
I'm trying to get a minimal Vizceral component displaying in a React/Material UI application, but the canvas is always height = 0 (canvas height, not style height):

```html
<div class="vizceral">
  <canvas width="1325" height="0" style="width: 100%; height: 100%; touch-action: manipulation; -webkit-user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: auto;"></canvas>
  <div class="vizceral-notice" style="display: none;"></div>
  <div class="context INTERNET" style="position: absolute; display: block;"></div>
  <div class="context us-west-2" style="position: absolute; display: block; width: 191.389px; left: 5.65776px; height: 124.403px; top: 151.243px;"></div>
</div>
```

If I go into via Chrome dev tools and change the height to 1000 (or any non-zero number), I get the nodes, but no animated traffic. I've been comparing my code to the example application, and cannot for the life of me figure out what the difference is. 

Here's my code:

```jsx
import React, {Component} from 'react'

import 'vizceral-react/dist/vizceral.css';
import Vizceral from 'vizceral-react';

const traffic = JSON.parse('{"connections":[{"source":"INTERNET","target":"us-west-2","metrics":{"normal":9000,"warning":500,"danger":500},"volume":10000}],"nodes":[{"renderer":"region","name":"INTERNET","nodes":[],"class":"normal","maxVolume":10000},{"renderer":"region","name":"us-west-2","nodes":[],"class":"normal","maxVolume":10000}],"name":"edge","renderer":"global"}');

export default class Welcome extends Component {
  render() {
    return (
      <div className="welcome-container">
        <div className="welcome">
          <Vizceral view={[]} showLabels={true} traffic={traffic} />
        </div>
      </div>
    )
  }
}
```

Is there another dependency that I need to explicitly install or something? 

Here's mine, in case anything jumps out at you:

```json
"dependencies": {
    "babel-polyfill": "^6.8.0",
    "isomorphic-fetch": "^2.2.1",
    "keymirror": "^0.1.1",
    "lodash": "^4.12.0",
    "material-ui": "^0.15.0",
    "moment": "^2.13.0",
    "mousetrap": "^1.5.3",
    "react": "^15.0.2",
    "react-dom": "^15.0.2",
    "react-redux": "^4.4.5",
    "react-router": "^2.4.0",
    "react-router-redux": "^4.0.4",
    "react-tap-event-plugin": "^1.0.0",
    "redux": "^3.5.2",
    "redux-form": "^5.2.3",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.1.0",
    "validator": "^5.2.0",
    "vizceral-react": "^2.4.0"
  }
```

Thanks!

**Comment by jrsquared** [comment]
Does `.welcome` have any height specified? If `.welcome` has a height specified as a percentage, `.welcome-container` have a height specified? The Vizceral component just tries to fill the size of the enclosing `div`.

**Comment by rickfast** [comment]
Yeah I'm an idiot. I set a specific size on an enclosing div and I'm good there. I still don't get any particles on the high level view though. I pulled in the props from vizceral-example and no animation. If I click us-west-2 or another region, the animation works fine for the service level view. Any idea what could be causing the animation to not start? Thanks again

**Comment by jrsquared** [comment]
Fun race condition when passing in data directly without an asynchronous call to retrieve it. Let me know if you still it!

**Comment by rickfast** [comment]
Yup. Started working after I hooked it up to the backend. Thanks

**Comment by jrsquared** [comment]
To be clear, I believe I fixed it for your example use case as well with commit e10cf23, but glad you got it working with the backend!

**Comment by jasonwr** [comment]
@jrsquared believe it or not this is still an issue in the main Vizceral project where once the canvas loads with the graph data the width gets maxed and the height is still zero. I have this set:

`<canvas id="vizceral" style="width: 100%;height: 100%"></canvas>`

**Comment by jasonwr** [comment]
@jrsquared What I ended up doing is save the original width and height of the canvase, then perform a resize on the canvas after the animate and this works, but really it should be resolved in the main source as this is definitely a bug.

**Comment by jrsquared** [comment]
@jasonwr Vizceral will control the width and height of the canvas.  It will set the canvas' height to be 100% of the parent container.  If the parent container does not have a known height, the canvas will always be resized to 0.

All you have to do is make sure the enclosing container has a valid height.
